name: Autobuild for Docker

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install builder plugin
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
        run: |
          docker buildx build --push \
            --tag "${{secrets.DOCKER_TAG}}" \
            --platform linux/amd64 .
